import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/Header/NavBarComponent/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-full">
          <NavBar />
        </header>
        <main className="relative flex flex-col items-center w-screen h-auto min-h-screen">
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
